/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#001e2c",
        "on-secondary-container": "#00516f",
        "inverse-surface": "#2e3132",
        "delivery-green": "#008500",
        "primary-container": "#0f4fff",
        "tertiary-container": "#be2e01",
        tertiary: "#942100",
        secondary: "#00658b",
        "primary-fixed-dim": "#b8c3ff",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "secondary-fixed": "#c4e7ff",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#0048f5",
        "on-tertiary-fixed-variant": "#891e00",
        outline: "#747688",
        "surface-bright": "#f8f9fa",
        "rating-gold": "#FF9D3D",
        background: "#f8f9fa",
        "surface-container": "#edeeef",
        primary: "#0F4FFF",
        "on-background": "#191c1d",
        "on-surface-variant": "#434656",
        "secondary-container": "#5cc6fd",
        "surface-container-high": "#e7e8e9",
        "outline-variant": "#c3c5d9",
        surface: "#f8f9fa",
        "secondary-fixed-dim": "#7dd0ff",
        "text-secondary": "#555555",
        "inverse-primary": "#b8c3ff",
        "ai-purple": "#F1EEFB",
        "rocket-navy": "#003E94",
        "discount-orange": "#FF6303",
        "tertiary-fixed-dim": "#ffb4a1",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#004c69",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#ffdbd2",
        "primary-fixed": "#dde1ff",
        "surface-dim": "#d9dadb",
        "on-primary-fixed": "#001355",
        "on-primary": "#ffffff",
        "on-primary-container": "#dde1ff",
        "text-primary": "#111111",
        "border-gray": "#E2E5E8",
        "on-tertiary-fixed": "#3c0800",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#ffdbd2",
        "on-primary-fixed-variant": "#0036bc",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-highest": "#e1e3e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "24px",
        "stack-sm": "4px",
        "stack-md": "8px",
        "stack-lg": "16px",
        "container-margin": "16px",
        gutter: "12px",
        "margin-mobile": "16px",
        xs: "4px",
        sm: "8px",
        safe: "env(safe-area-inset-bottom)",
      },
      fontFamily: {
        sans: ["Inter", "Apple SD Gothic Neo", "Malgun Gothic", "sans-serif"],
      },
      fontSize: {
        "label-xs": ["10px", { lineHeight: "12px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "display-price": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg-medium": ["16px", { lineHeight: "22px", fontWeight: "500" }],
        "headline-sm-mobile": ["17px", { lineHeight: "22px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600", textTransform: "uppercase" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "body-lg-bold": ["16px", { lineHeight: "22px", fontWeight: "700" }],
        caption: ["10px", { lineHeight: "14px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
